version: ${VERSION}

logging:
  path: ${projectDir}/logs
  level:
    root: INFO
    com.nicepick.juicy: DEBUG

server:
  port: 80
  tomcat:
    accesslog:
      directory: \${logging.path}/tomcat
      enabled: true

spring.mvc.throw-exception-if-no-handler-found: true

taobao.api:
  app-key: ""
  app-secret: ""
  app-url: "http://gw.api.taobao.com/router/rest"
  world-url: "http://api.taobao.com/router/rest"

management:
  info.git.mode: full
  endpoints.web.exposure.include: env,health,httptrace,info,logfile,loggers,sessions
  metrics.export.prometheus.step: 10m
